In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
dataset=pd.read_csv("Self Awareness Dataset-2.csv")

In [32]:
dataset.head()

Date       Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
0  14-Jan    Friday         5.0            1.0         2.0           0.0   
1  15-Jan  Saturday         5.0            0.0         0.0           0.0   
2  16-Jan    Sunday         8.0            1.0         1.0           0.0   
3  17-Jan    Monday         3.0            1.0         5.0           3.0   
4  18-Jan   Tuesday         7.0            1.0         5.0           1.0   

   Work Hour  End of the day Feeling (0 to 10)  
0        7.0                               6.0  
1        2.0                               4.0  
2       12.0                               5.0  
3        4.0                               8.0  
4        5.5                              10.0

In [33]:
dataset.drop(['Date','Day'], axis=1, inplace=True)

In [34]:
dataset.columns

Index(['Sleep Hour', 'Exercise Hour', 'Study Hour', 'StudyDS Hour',
       'Work Hour', 'End of the day Feeling (0 to 10)'],
      dtype='object')

In [35]:
dataset.isnull().sum()

Sleep Hour                          1
Exercise Hour                       1
Study Hour                          1
StudyDS Hour                        1
Work Hour                           1
End of the day Feeling (0 to 10)    1
dtype: int64

In [55]:
dataset['Sleep Hour'].fillna(dataset['Sleep Hour'].mode()[0], inplace=True)

In [56]:
dataset['Exercise Hour'].fillna(dataset['Exercise Hour'].mode()[0], inplace=True)

In [57]:
dataset['Study Hour'].fillna(dataset['Study Hour'].mode()[0], inplace=True)

In [58]:
dataset['StudyDS Hour'].fillna(dataset['StudyDS Hour'].mode()[0], inplace=True)

In [59]:
dataset['Work Hour'].fillna(dataset['Work Hour'].mode()[0], inplace=True)

In [60]:
dataset['End of the day Feeling (0 to 10)'].fillna(dataset['End of the day Feeling (0 to 10)'].mode()[0], inplace=True)

In [61]:
dataset.isnull().sum()

Sleep Hour                          0
Exercise Hour                       0
Study Hour                          0
StudyDS Hour                        0
Work Hour                           0
End of the day Feeling (0 to 10)    0
dtype: int64

In [62]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Sleep Hour                        66 non-null     float64
 1   Exercise Hour                     66 non-null     float64
 2   Study Hour                        66 non-null     float64
 3   StudyDS Hour                      66 non-null     float64
 4   Work Hour                         66 non-null     float64
 5   End of the day Feeling (0 to 10)  66 non-null     float64
dtypes: float64(6)
memory usage: 3.2 KB


In [63]:
dataset.columns

Index(['Sleep Hour', 'Exercise Hour', 'Study Hour', 'StudyDS Hour',
       'Work Hour', 'End of the day Feeling (0 to 10)'],
      dtype='object')

In [64]:
X=dataset.iloc[::-1].values
y=dataset.iloc[:-1].values

In [65]:
X=dataset[['Sleep Hour', 'Exercise Hour', 'Study Hour', 'StudyDS Hour', 'Work Hour']]
y=dataset[['End of the day Feeling (0 to 10)']]

In [66]:
X.head()

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour
0         5.0            1.0         2.0           0.0        7.0
1         5.0            0.0         0.0           0.0        2.0
2         8.0            1.0         1.0           0.0       12.0
3         3.0            1.0         5.0           3.0        4.0
4         7.0            1.0         5.0           1.0        5.5

In [67]:
y.head()

End of the day Feeling (0 to 10)
0                               6.0
1                               4.0
2                               5.0
3                               8.0
4                              10.0

In [87]:
X=pd.get_dummies(dataset[['Sleep Hour','Exercise Hour','Study Hour','StudyDS Hour',
                          'Work Hour']],drop_first=True)

In [88]:
X.head()

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour
0         5.0            1.0         2.0           0.0        7.0
1         5.0            0.0         0.0           0.0        2.0
2         8.0            1.0         1.0           0.0       12.0
3         3.0            1.0         5.0           3.0        4.0
4         7.0            1.0         5.0           1.0        5.5

In [89]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=.2, random_state=0)

In [90]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [91]:
print("Coefficients",regressor.coef_)

Coefficients [[ 0.14172934 -0.34450306  1.28138604 -0.89795903 -0.06469491]]


In [92]:
print("intercept", regressor.intercept_)

intercept [2.52608722]


In [93]:
y_pred=regressor.predict(X_test)

In [94]:
regressor.predict([[7,1,5,1,5.5]])

array([[8.32683876]])

In [95]:
regressor.predict([[4,1,4,1,3]])

array([[6.78200196]])

In [96]:
regressor.predict([[4,1,0,0,0]])

array([[2.74850153]])

In [97]:
regressor.predict([[6,1,5,1,5.5]])

array([[8.18510942]])

In [98]:
regressor.predict([[3,1,5,3,4]])

array([[6.06104569]])

In [99]:
from sklearn.metrics import r2_score
print("r2_score",r2_score(y_test,y_pred))

r2_score 0.09092225774583029


In [100]:
import statsmodels.api as sm
X=sm.add_constant(X)

In [101]:
model=sm.OLS(y,X).fit()

In [102]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                   OLS Regression Results                                   
============================================================================================
Dep. Variable:     End of the day Feeling (0 to 10)   R-squared:                       0.446
Model:                                          OLS   Adj. R-squared:                  0.400
Method:                               Least Squares   F-statistic:                     9.668
Date:                              Tue, 22 Mar 2022   Prob (F-statistic):           8.31e-07
Time:                                      01:59:02   Log-Likelihood:                -131.61
No. Observations:                                66   AIC:                             275.2
Df Residuals:                                    60   BIC:                             288.4
Df Model:                                         5                                         
Covariance Type:                          nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             2.5978      1.672      1.554      0.126      -0.747       5.942
Sleep Hour        0.1253      0.220      0.568      0.572      -0.316       0.566
Exercise Hour    -0.3582      1.257     -0.285      0.777      -2.872       2.156
Study Hour        1.1827      0.195      6.077      0.000       0.793       1.572
StudyDS Hour     -0.7634      0.336     -2.270      0.027      -1.436      -0.091
Work Hour        -0.0247      0.094     -0.263      0.793      -0.212       0.163
==============================================================================
Omnibus:                        0.154   Durbin-Watson:                   1.091
Prob(Omnibus):                  0.926   Jarque-Bera (JB):                0.229
Skew:                          -0.109   Prob(JB):                        0.892
Kurtosis:                       2.810   Cond. No.                         70.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""